package UNO;

public enum Type {
    YELLOW, YELLOW_REVERSE, YELLOW_PLUS2, YELLOW_PASS, BLUE, BLUE_REVERSE, BLUE_PLUS2, BLUE_PASS, GREEN, GREEN_PLUS2, GREEN_PASS, GREEN_REVERSE, RED, RED_PLUS2, RED_REVERSE, RED_PASS, PLUS_4, COLORCHANGE

}
